
### Landing page
GET http://localhost:2

### Shoe inventory
GET http://localhost:2/shoes

### Inventory by id
GET http://localhost:2/shoes/65f89b7cba201e283e19b657

### Add a shoe
POST http://localhost:2/shoes HTTP/1.1
content-type: application/json

{
  "brand": "needed",
  "line": "needed",
  "model": "needed",
  "height": "needed",
  "colors": "needed"
}

### PUT- Update shoe
PUT http://localhost:2/shoes/65f91d8be93277b596986af5
content-type: application/json

{
  "brand": "probably",
  "line": "probably",
  "model": "probably",
  "height": "probably",
  "colors": "probably"
}

### Delete shoe
DELETE http://localhost:2/shoes/65f91d8be93277b596986af5